DROP TABLE IF EXISTS UserLevelProgress;
DROP TABLE IF EXISTS QuizQuestion;
DROP TABLE IF EXISTS LevelQuiz;
DROP TABLE IF EXISTS Quiz;
DROP TABLE IF EXISTS Level;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    UserID SERIAL PRIMARY KEY,
    Username VARCHAR(100) NOT NULL,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Email VARCHAR(150) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    UserRole CHAR(1) NOT NULL DEFAULT 'S',
    Streak INTEGER DEFAULT 0
);

CREATE TABLE Level (
    LevelID SERIAL PRIMARY KEY,
    LevelName VARCHAR(100) NOT NULL,
    Difficulty INTEGER NOT NULL,
    Description VARCHAR(255),
    Instructions VARCHAR(255)
);

CREATE TABLE Quiz (
    QuizID SERIAL PRIMARY KEY,
    QuizNumber INTEGER NOT NULL,
    Question VARCHAR(255) NOT NULL,
    PassingScore VARCHAR(50) NOT NULL
);

CREATE TABLE LevelQuiz (
    LevelQuizID SERIAL PRIMARY KEY,
    LevelName VARCHAR(100) NOT NULL,
    QuizID INTEGER NOT NULL REFERENCES Quiz(QuizID)
);

CREATE TABLE QuizQuestion (
    QuestionID SERIAL PRIMARY KEY,
    QuizID INTEGER NOT NULL REFERENCES Quiz(QuizID),
    Question VARCHAR(255) NOT NULL,
    QuestionType VARCHAR(50) NOT NULL,
    PointValue INTEGER NOT NULL
);

CREATE TABLE UserLevelProgress (
    ProgressID SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL REFERENCES Users(UserID),
    LevelID INTEGER NOT NULL REFERENCES Level(LevelID),
    StartDate TIMESTAMP DEFAULT NOW(),
    CompletionDate TIMESTAMP,
    Status VARCHAR(50) NOT NULL DEFAULT 'In Progress',
    Score INTEGER DEFAULT 0
);
